[feature] notice 관련 기능 구현
COW-dev/eat-da-be pull request #16
Opened 2023-09-27 07:21 UTC by k-kbk

## 해당 PR이 어떤 것을 하나요?

- notice 기본 CRUD 기능 구현

## 고민(선택)

- id가 nullable해서 null aseertion(!!)을 계속 사용해야 하는게 조금 찝찝하다(그래서 우테코에서는 0L로 쓰는 듯?)
- update 개선?

## 기획 문서 혹은 태스크 관련 링크

2023-09-29 10:14 UTC, dojinyou requested changes
[cateogry pr](https://github.com/COW-dev/eat-da-be/pull/18) 참고해서 update하고 다시 리뷰 요청해주세연

2023-09-29 11:37 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/entity/Notice.kt
> +) : BaseEntity()
제약 조건 추가하고 검증 로직 추가 set와 secondary 생성자를 이용해서 검증하기

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
> +    @Throws(EntityNotFoundException::class)
요건 뭐하는 어노테이션이야?

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
> +    fun update(noticeId: Long, request: UpdateNoticeCommand) {
```suggestion
    fun update(noticeId: Long, command: UpdateNoticeCommand) {
```

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/UpdateNoticeCommand.kt
> +    val content: String?,
둘 다 NotNull로 하고 변경 없어도 기존 값 넣어주도록 하는게 더 좋을거 같음!

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
> +}
이거 왜 자동으로 바뀌지?!

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/dto/CreateNoticeCommand.kt
> +    @field:NotBlank(message = "공지사항 제목은 필수 입력 값입니다.")
validation은 entity에서 집중해서 하는 게 좋을듯

validation.constraints를 controller가 아닌 쪽에서 동작하게 하려면 추가적인 어노테이션들이 필요함!
지금 service에서도 이걸 쓰고 있어서 controller에서 생성해서 넘겨주면 validate가 동작하지 않음

2023-09-29 11:51 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
> +        val notice = repository.findByIdOrNull(noticeId) ?: throw IllegalArgumentException()
없는 것도 삭제된 거랑 똑같이 동작하게 해서 멱등성 보장
```suggestion
        val notice = repository.findByIdOrNull(noticeId) ?: return
```

2023-09-30 12:01 UTC, k-kbk commented on src/main/kotlin/com/mjucow/eatda/presentation/store/category/CategoryController.kt
> +}
어라 저는 ktlint 돌리면 마지막 줄 공백이 추가되네요

2023-09-30 12:03 UTC, k-kbk commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
> +    @Throws(EntityNotFoundException::class)
https://velog.io/@sujin-create/kotlin-exception

예외처리 할 때 써줘야하는 줄 알았는데 알고보니 상호운용성을 위해서 사용하는 거였네요

2023-10-12 12:21 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/dto/NoticeDto.kt
> +) {
Notice 내려갈 때 createdAt도 내려가야되나 싶기도 하고? api 한번 봐야될듯

2023-10-12 12:23 UTC, dojinyou commented on src/test/resources/application.yml
> +logging.config: classpath:logback-test.xml
일반 파일 개행문자 체크!

2023-10-13 01:45 UTC, dojinyou approved these changes
ㄱㄱ

2023-10-13 01:45 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/command/NoticeCommandService.kt
> +        repository.save(notice)
[nit] 이미 업데이트 되어진 것 변수에 나타내기?!
```suggestion
        val updatedNotice = repository.findByIdOrNull(noticeId)?.apply {
            title = newTitle
            content = newContent
        } ?: throw IllegalArgumentException()

        repository.save(updatedNotice)
```

2023-10-13 01:45 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryService.kt
> +        return Notices(repository.findAllByOrderByIdDesc().map(NoticeDto::from))
요거 나중에 쿼리 나가는거 보고 실행계획도 한번 보면 좋을듯? 실제로 어떻게 동작할지 약간 헷갈림 ㅋㅋㅋ

2023-10-13 01:45 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/notice/service/query/NoticeQueryService.kt
> +        return NoticeDto.from(notice)
이것도 이렇게해도 되겠다 ㅋㅋㅋㅋ
```suggestion
        return repository.findByIdOrNull(noticeId)?.let {
          NoticeDto.from(it)
        } ?: throw EntityNotFoundException("공지사항이 존재하지 않습니다.")
```

2023-10-15 05:01 UTC, merged