[feature] banner 도메인 구현 및 테스트 코드 작성
COW-dev/eat-da-be pull request #36
Opened 2023-10-17 15:06 UTC by k-kbk

## 해당 PR이 어떤 것을 하나요?

- banner 도메인 구현 및 테스트 코드 작성

## 고민(선택)
- order 관련 기능(추가 예정)

## 기획 문서 혹은 태스크 관련 링크

2023-10-17 15:29 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/banner/entity/Banner.kt
> +    }
order는 주석으로 어떻게 업데이트하면 좋을 지가 필요할듯!

2023-10-17 15:29 UTC, dojinyou commented on src/main/resources/db/changelog/231016-banner.sql
> +    "order"       smallint     NOT NULL,
예약어면 `order` 말고 displayOrder?

2023-10-17 15:29 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/banner/entity/Banner.kt
> +    }
필요하다면 expiredAt 같은거 넣어도 되고?! 전체적인 banner의 lifecycle 정의가 필요해보임!

2023-11-04 10:02 UTC, dojinyou requested changes
banner의 순서는 어떻게 정의할 지?
지금 같은 구조에서는 banner table의 데이터가 증가하게 됨! (expired 된 데이터를 지우지 않는 한) 그러면 꾸준히 banner 조회를 위한 시간이 늘어나게 될텐데 어떻게 하면 좋을 지?! expiredAt에 index를 걸기엔 cardinality가 너무 낮음!

2023-11-06 05:01 UTC, dojinyou reviewed
하루에 한번 돌아가면서 expiredAt 된 banner 옮기는 job 필요할 것 같음! 
notion backlog에 추가해놓기

2023-11-06 05:01 UTC, dojinyou commented on src/main/resources/db/changelog/231105-expired_banner.sql
> +    expired_at    timestamp,
여기선 notNull?

2023-11-06 05:01 UTC, dojinyou commented on src/main/resources/db/changelog/231105-expired_banner.sql
> +    updated_at    timestamp    NOT NULL
요거 필요하려나?!

2023-11-06 05:01 UTC, dojinyou reviewed
하루에 한번 돌아가면서 expiredAt 된 banner 옮기는 job 필요할 것 같음! 
notion backlog에 추가해놓기

2023-11-06 05:12 UTC, k-kbk commented on src/main/resources/db/changelog/231105-expired_banner.sql
> +    expired_at    timestamp,
뭔가 이제 유효기간 없던 애도 언젠가 만료 처리 해버리고 싶지 않을까 싶어서? 약간 보관용으로?

2023-11-06 05:42 UTC, dojinyou approved these changes
👍

2023-11-06 05:42 UTC, dojinyou commented on src/main/resources/db/changelog/231105-expired_banner.sql
> +CREATE TABLE expired_banner
요 녀석도 엔티티는 만들어둔다?!

2023-11-06 05:57 UTC, k-kbk commented on src/main/resources/db/changelog/231105-expired_banner.sql
> +CREATE TABLE expired_banner
넹

2023-11-06 05:57 UTC, merged