[refactor] (Point,PhoneNumber)primitive value -> VO Class
COW-dev/eat-da-be pull request #76
Opened 2023-12-23 13:48 UTC by 0702Yoon

## 해당 PR이 어떤 것을 하나요?

Point의 latitude와 longitude를 Double값으로 바로 받는 것이 아닌 Latitude ,Longitude의 value class로 받게 했다.
PhoneNumber 같은 경우는 Data class로 불변과 equals, hashjCode의 재정의가 이미 되어있어, 정규표현식에서 번호가 3인 것 까지 받게만 변경하였다.
## 고민(선택)
1. @Embeddable, @JsonDeserialize 등의 기존 코드의 이해
2. data class와 value class의 이해
3. @Embeddable의 필드에는 JPA가 지원하는 타입만 올 수 있고 그것을 해결한 방법은 value class,@JvmInline

## 기획 문서 혹은 태스크 관련 링크

2023-12-23 14:04 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
> +        val NUMBER_REGEX = Regex("^0\\d{1,3}[-)]\\d{3,4}-\\d{4}\$")
요건 왜 3으로 바꼈나요?!

2023-12-23 14:05 UTC, 0702Yoon commented on src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
> +        val NUMBER_REGEX = Regex("^0\\d{1,3}[-)]\\d{3,4}-\\d{4}\$")
앞에 전화번호가 3인 지역번호도 존재해서 추가했습니다. 혹시 가게는 서울한정으로만 하는 건가요??

2023-12-23 14:06 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
> +        val NUMBER_REGEX = Regex("^0\\d{1,3}[-)]\\d{3,4}-\\d{4}\$")
아뇨! 앞에 0이 prefix로 있어서 2자리도 괜찮지 않을까요?

2023-12-23 14:08 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/deseializer/Latitude.kt
> +package com.mjucow.eatda.common.vo.deseializer
vo로 바로 써도 될 것 같아서 패키지 이동해야될 것 같아요
```suggestion
package com.mjucow.eatda.common.vo
```

2023-12-23 14:08 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/deseializer/Latitude.kt
> +    }
이쪽에서 검증하는 로직들은 테스트 코드 필요할 것 같아요.

2023-12-23 14:10 UTC, 0702Yoon commented on src/main/kotlin/com/mjucow/eatda/common/vo/PhoneNumber.kt
> +        val NUMBER_REGEX = Regex("^0\\d{1,3}[-)]\\d{3,4}-\\d{4}\$")
저번에도 second를 minute로 보더니,,숫자 2만 보고 왜 두글자만 하셨지란 생각에 빠져서.. 다시 고치겠습니다

2023-12-23 14:11 UTC, 0702Yoon commented on src/main/kotlin/com/mjucow/eatda/common/vo/deseializer/Latitude.kt
> +package com.mjucow.eatda.common.vo.deseializer
넵

2023-12-23 14:11 UTC, 0702Yoon commented on src/main/kotlin/com/mjucow/eatda/common/vo/deseializer/Latitude.kt
> +    }
테스트 코드 공부해서 적용해보겠습니다

2024-01-09 14:32 UTC, dojinyou requested changes

2024-01-09 14:32 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/Latitude.kt
> +        }
- 상수 처리하기 -> 가독성 향상(매직 넘버)
- 코틀린은 상관없음(하지만 자바라면 항상 값이 있는 값을 왼쪽에 둔다)

2024-01-09 14:32 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
> +class LatitudeTest : VOTest {
```suggestion
import org.junit.jupiter.params.provider.MethodSource

class LatitudeTest : VOTest {
```

2024-01-09 14:32 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
> +    @MethodSource("validValues")
MethodSource 적용 잘하셨습니다. 다만 기본 타입읜 `@ValueSource(doubles = [0.0, 1.0])` 와 같은 형태로 제공해도 충분할 것 같아요!

2024-01-09 14:32 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
> +    @MethodSource("validValues")
테스트 케이스는 경계값을 기준으로 1 unit 기준 잡아서 전후로 테스트하시면 좋습니다.
ex) 물의 온도라고 하면 0과 100이 경계값이라면 아래와 같이 테스트 케이스를 잡으면 편리합니다.
`Interger.MIN_VALUE, -1, 0, 1, 99, 100, 101, Integer.MAX_VALUE`

2024-01-09 14:32 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
> +    companion object {
`companion object`는 제일 밑으로 내려주시는게 kotlin 컨벤션입니다.

2024-01-14 14:16 UTC, dojinyou approved these changes
네이밍 수정하고 범위만 줄이고 머지해주세요

2024-01-14 14:16 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/common/vo/Latitude.kt
> +        private const val LATITUDE_MAX = 90.0
국내로 더 좁혀도 될듯함!

2024-01-14 14:16 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LatitudeTest.kt
> +
```suggestion
```

2024-01-14 14:16 UTC, dojinyou commented on src/test/kotlin/com/mjucow/eatda/common/vo/LongitudeTest.kt
> +    @DisplayName("위도의 범위가 올바르면 객체가 생성된다.")
생성이 안되어야 될듯!

2024-01-18 07:32 UTC, merged