[refactor] 큐레이션 도메인 수정 및 API 추가
COW-dev/eat-da-be pull request #89
Opened 2024-02-14 07:18 UTC by Gopistol

## 해당 PR이 어떤 것을 하나요?

큐레이션 가게 스크롤 API 추가 
- `GET /v1/curations/:id/stores?cursor=3&pageSage=20`

## 고민(선택)

StoreCustomRepositoryImpl 에서 추가된 `findIdsByCurationIdOrderByIdDesc` 관련 테스트 코드는 작성하지 않았는데,
기존의 `findIdsByCategoryIdOrderByIdDesc` 메소드와 같은 로직이어서 고민됩니다.

## 기획 문서 혹은 태스크 관련 링크

2024-02-15 03:35 UTC, dojinyou requested changes
테스트 깨지는 것도 챙겨주세요

2024-02-15 03:35 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
> +    }
p2) 큐레이션쪽에는 curationId를 필수로 받으면 좋을 것 같아요!

2024-02-15 09:33 UTC, Gopistol commented on src/main/kotlin/com/mjucow/eatda/domain/store/service/query/StoreQueryService.kt
> +    }
기존 메소드에서도 커서만 받는 게 있어서
 큐레이션은 필수로 받는게 더 나을거같네용 수정하겠습니다

2024-03-01 10:59 UTC, dojinyou approved these changes

2024-03-01 10:59 UTC, dojinyou commented on src/main/resources/db/changelog/240129-curation.sql
> -    updated_at    timestamp    NOT NULL
이미 나간 건 수정하면 안됨!
밑에 add column 쪽에 Default NOW() Alter column으로 추가해

2024-03-01 10:59 UTC, dojinyou commented on src/main/kotlin/com/mjucow/eatda/presentation/curation/CurationApiPresentation.kt
> +    @Operation(summary = "큐레이션별 가게 전체 조회", description = "한 큐레이션에 있는 모든 가게를 조회합니다.")
```suggestion
    @Operation(summary = "큐레이션별 가게 전체 조회", description = "특정 큐레이션에 있는 모든 가게를 조회합니다.")
```

2024-03-02 06:24 UTC, merged